language: node_js
node_js:
- iojs
- '7'
deploy:
  provider: cloudfoundry
  api: https://api.fr.cloud.gov
  username: dweaver@topcoder.com
  password:
    secure: iJ8fUuBVHMSmt7xaho+OKDUIgDW/DrP5ggjiCUgSQKBbVaq1npa+EuHor1vQBOTCVmzlvR0gzPXPmZTTsNw82+gyP0OSf+nF/yFXhDnsGGFl4u68COhmi0L3Qe3oixxe7csWcauXrQUBt7gsj2+IocilS4FagjbkzimTY51A/o0QyISRibIIXGMF+2ou3R3mIzTJZBzS2zD1V7zkuVdzIPIZ3c3IIkoYUTAummJ6XtPzNJ2HkT4HPzxqpPZg/sE39nmuWtn/YM49Q3c6vEUOLM7yDr3ZmHpgKBZWuyIxMI9IOprwl3wDnmCIxK1f6y809l4uuX4r41SZVQa3VfH+kG171n7q/GU3X0ln22WY08AgWZogt3j486UZScEfv3iGMc0wiWVGy6LNb21T8vBAKhuTS15Ujtud9frY8vvyYWN/SginH/fPdSqd5j3hdbgo6YGoG9R7l6O/+74dJiNZX58xBoizs4ZzmrmsFAcTKyFr5gZe8a2/u6WqJ+LAnjPGntEKifgj4zB7Z0GeFnryJlYHM76p1HypmRbkO3JMs6T1E878ar6NbY+TUUAJWf6Cq7cWDwNNrf4Bd+wSx5tTbdpFQbztJVdPh+rCU/N6rlxfmrUCa4gfIxovIbN/lYLZmnban9AKhpKT6r4AzTIewULkoaNiwbwDNqhNSANftME=
  organization: sandbox-va
  space: frontend
  on:
    repo: topcoderinc/va-online-memorial-frontend
    branch: prototype
